-- Materials / chemicals / equipment catalog for the internal Materialien module
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.report_checklist_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category text NOT NULL CHECK (category IN ('chemie', 'geraete', 'materialien', 'hinweise')),
  name text NOT NULL,
  description text,
  warning text,
  safety_sheet_url text,
  active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.report_checklist_items
  ADD COLUMN IF NOT EXISTS category text,
  ADD COLUMN IF NOT EXISTS name text,
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS warning text,
  ADD COLUMN IF NOT EXISTS safety_sheet_url text,
  ADD COLUMN IF NOT EXISTS active boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_report_checklist_items_category
  ON public.report_checklist_items(category, active, name);

ALTER TABLE public.report_checklist_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Checklist read active" ON public.report_checklist_items;
DROP POLICY IF EXISTS "Checklist admin insert" ON public.report_checklist_items;
DROP POLICY IF EXISTS "Checklist admin update" ON public.report_checklist_items;
DROP POLICY IF EXISTS "Checklist admin delete" ON public.report_checklist_items;

CREATE POLICY "Checklist read active"
  ON public.report_checklist_items
  FOR SELECT
  TO authenticated
  USING (active = true OR lower(auth.jwt() ->> 'email') = 'mtclemur@gmail.com');

CREATE POLICY "Checklist admin insert"
  ON public.report_checklist_items
  FOR INSERT
  TO authenticated
  WITH CHECK (lower(auth.jwt() ->> 'email') = 'mtclemur@gmail.com');

CREATE POLICY "Checklist admin update"
  ON public.report_checklist_items
  FOR UPDATE
  TO authenticated
  USING (lower(auth.jwt() ->> 'email') = 'mtclemur@gmail.com')
  WITH CHECK (lower(auth.jwt() ->> 'email') = 'mtclemur@gmail.com');

CREATE POLICY "Checklist admin delete"
  ON public.report_checklist_items
  FOR DELETE
  TO authenticated
  USING (lower(auth.jwt() ->> 'email') = 'mtclemur@gmail.com');

INSERT INTO public.report_checklist_items (category, name, description, warning)
VALUES
  ('chemie', 'Allzweckreiniger', 'Universeller Unterhaltsreiniger.', 'Bodenvertraeglichkeit vor Anwendung pruefen.'),
  ('chemie', 'Sanitaerreiniger', 'Reiniger fuer Sanitaerbereiche.', 'Nicht auf saeureempfindlichen Oberflaechen verwenden.'),
  ('chemie', 'Grundreiniger', 'Reiniger fuer Grundreinigung.', 'Schutzkleidung und Sicherheitsdatenblatt beachten.'),
  ('geraete', 'Einscheibenmaschine', 'Maschine fuer Grundreinigung und Pflege.', NULL),
  ('geraete', 'Nasssauger', 'Geraet zum Absaugen von Schmutzflotte.', NULL),
  ('geraete', 'Scheuersaugmaschine', 'Maschine fuer maschinelle Bodenreinigung.', NULL),
  ('materialien', 'Pads', 'Reinigungspads nach Bodenart.', 'Pad passend zum Bodenbelag waehlen.'),
  ('materialien', 'Mikrofasertuecher', 'Tuchmaterial fuer Oberflaechenreinigung.', NULL),
  ('materialien', 'Muellsaecke', 'Verbrauchsmaterial.', NULL)
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS public.material_usage_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL DEFAULT auth.uid(),
  user_email text,
  worker_name text,
  item_id uuid REFERENCES public.report_checklist_items(id) ON DELETE SET NULL,
  category text NOT NULL CHECK (category IN ('chemie', 'geraete', 'materialien', 'hinweise')),
  item_name text NOT NULL,
  quantity numeric,
  unit text,
  usage_date date NOT NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.material_usage_entries
  ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL DEFAULT auth.uid(),
  ADD COLUMN IF NOT EXISTS user_email text,
  ADD COLUMN IF NOT EXISTS worker_name text,
  ADD COLUMN IF NOT EXISTS item_id uuid REFERENCES public.report_checklist_items(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS category text,
  ADD COLUMN IF NOT EXISTS item_name text,
  ADD COLUMN IF NOT EXISTS quantity numeric,
  ADD COLUMN IF NOT EXISTS unit text,
  ADD COLUMN IF NOT EXISTS usage_date date,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_material_usage_date
  ON public.material_usage_entries(usage_date, category, item_name);
CREATE INDEX IF NOT EXISTS idx_material_usage_user
  ON public.material_usage_entries(user_id, usage_date);

ALTER TABLE public.material_usage_entries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Material usage select allowed" ON public.material_usage_entries;
DROP POLICY IF EXISTS "Material usage insert own" ON public.material_usage_entries;
DROP POLICY IF EXISTS "Material usage update own" ON public.material_usage_entries;
DROP POLICY IF EXISTS "Material usage delete own" ON public.material_usage_entries;

CREATE POLICY "Material usage select allowed"
  ON public.material_usage_entries
  FOR SELECT
  TO authenticated
  USING (
    lower(auth.jwt() ->> 'email') = 'mtclemur@gmail.com'
    OR auth.uid() = user_id
  );

CREATE POLICY "Material usage insert own"
  ON public.material_usage_entries
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() IS NOT NULL AND user_id = auth.uid());

CREATE POLICY "Material usage update own"
  ON public.material_usage_entries
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() IS NOT NULL AND user_id = auth.uid());

CREATE POLICY "Material usage delete own"
  ON public.material_usage_entries
  FOR DELETE
  TO authenticated
  USING (
    auth.uid() = user_id
    OR lower(auth.jwt() ->> 'email') = 'mtclemur@gmail.com'
  );

NOTIFY pgrst, 'reload schema';
