-- Voqenti Inventar & Bedarf
-- Run this in Supabase SQL Editor.
-- Adds separate Materialbedarf requests and equipment checkout/return workflow.

CREATE TABLE IF NOT EXISTS public.material_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  category text DEFAULT 'verbrauchsmaterial',
  unit text,
  image_url text,
  active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.material_items
  ADD COLUMN IF NOT EXISTS name text,
  ADD COLUMN IF NOT EXISTS category text DEFAULT 'verbrauchsmaterial',
  ADD COLUMN IF NOT EXISTS unit text,
  ADD COLUMN IF NOT EXISTS image_url text,
  ADD COLUMN IF NOT EXISTS active boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_material_items_active_name
  ON public.material_items(active, name);

CREATE TABLE IF NOT EXISTS public.material_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  objekt_id uuid,
  objekt_name text,
  auftrag_id text,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL DEFAULT auth.uid(),
  reporter_name text,
  reporter_email text,
  request_date date NOT NULL DEFAULT CURRENT_DATE,
  status text NOT NULL DEFAULT 'offen' CHECK (status IN ('offen', 'geplant', 'eingepackt', 'mitgenommen', 'erledigt')),
  note text,
  summary_sent boolean DEFAULT false,
  summary_sent_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.material_requests
  ADD COLUMN IF NOT EXISTS objekt_id uuid,
  ADD COLUMN IF NOT EXISTS objekt_name text,
  ADD COLUMN IF NOT EXISTS auftrag_id text,
  ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL DEFAULT auth.uid(),
  ADD COLUMN IF NOT EXISTS reporter_name text,
  ADD COLUMN IF NOT EXISTS reporter_email text,
  ADD COLUMN IF NOT EXISTS request_date date DEFAULT CURRENT_DATE,
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'offen',
  ADD COLUMN IF NOT EXISTS note text,
  ADD COLUMN IF NOT EXISTS summary_sent boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS summary_sent_at timestamptz,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_material_requests_date_status
  ON public.material_requests(request_date, status, summary_sent);
CREATE INDEX IF NOT EXISTS idx_material_requests_user
  ON public.material_requests(user_id, request_date);

CREATE TABLE IF NOT EXISTS public.material_request_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material_request_id bigint REFERENCES public.material_requests(id) ON DELETE CASCADE,
  material_item_id uuid REFERENCES public.material_items(id) ON DELETE SET NULL,
  custom_name text,
  quantity numeric,
  unit text,
  note text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.material_request_items
  ADD COLUMN IF NOT EXISTS material_request_id bigint REFERENCES public.material_requests(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS material_item_id uuid REFERENCES public.material_items(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS custom_name text,
  ADD COLUMN IF NOT EXISTS quantity numeric,
  ADD COLUMN IF NOT EXISTS unit text,
  ADD COLUMN IF NOT EXISTS note text,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_material_request_items_request
  ON public.material_request_items(material_request_id);

CREATE TABLE IF NOT EXISTS public.inventory_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  category text NOT NULL,
  image_url text,
  status text NOT NULL DEFAULT 'verfuegbar' CHECK (status IN ('verfuegbar', 'unterwegs', 'pruefen', 'beschaedigt')),
  active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.inventory_items
  ADD COLUMN IF NOT EXISTS name text,
  ADD COLUMN IF NOT EXISTS category text,
  ADD COLUMN IF NOT EXISTS image_url text,
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'verfuegbar',
  ADD COLUMN IF NOT EXISTS active boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_inventory_items_status
  ON public.inventory_items(status, active, category, name);

CREATE TABLE IF NOT EXISTS public.inventory_checkouts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inventory_item_id uuid REFERENCES public.inventory_items(id) ON DELETE CASCADE,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL DEFAULT auth.uid(),
  worker_name text,
  worker_email text,
  object_id uuid,
  object_name text,
  report_id bigint,
  taken_at timestamptz DEFAULT now(),
  returned_at timestamptz,
  return_clean boolean DEFAULT false,
  return_functional boolean DEFAULT false,
  return_note text,
  status text DEFAULT 'unterwegs',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.inventory_checkouts
  ADD COLUMN IF NOT EXISTS inventory_item_id uuid REFERENCES public.inventory_items(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL DEFAULT auth.uid(),
  ADD COLUMN IF NOT EXISTS worker_name text,
  ADD COLUMN IF NOT EXISTS worker_email text,
  ADD COLUMN IF NOT EXISTS object_id uuid,
  ADD COLUMN IF NOT EXISTS object_name text,
  ADD COLUMN IF NOT EXISTS report_id bigint,
  ADD COLUMN IF NOT EXISTS taken_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS returned_at timestamptz,
  ADD COLUMN IF NOT EXISTS return_clean boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS return_functional boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS return_note text,
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'unterwegs',
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_inventory_checkouts_open
  ON public.inventory_checkouts(returned_at, user_id, taken_at);

ALTER TABLE public.material_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.material_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.material_request_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_checkouts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Material items read" ON public.material_items;
DROP POLICY IF EXISTS "Material items admin write" ON public.material_items;
DROP POLICY IF EXISTS "Material requests select" ON public.material_requests;
DROP POLICY IF EXISTS "Material requests insert own" ON public.material_requests;
DROP POLICY IF EXISTS "Material requests update allowed" ON public.material_requests;
DROP POLICY IF EXISTS "Material request items select" ON public.material_request_items;
DROP POLICY IF EXISTS "Material request items insert" ON public.material_request_items;
DROP POLICY IF EXISTS "Inventory items read" ON public.inventory_items;
DROP POLICY IF EXISTS "Inventory items update allowed" ON public.inventory_items;
DROP POLICY IF EXISTS "Inventory checkouts select" ON public.inventory_checkouts;
DROP POLICY IF EXISTS "Inventory checkouts insert own" ON public.inventory_checkouts;
DROP POLICY IF EXISTS "Inventory checkouts update allowed" ON public.inventory_checkouts;

CREATE POLICY "Material items read"
  ON public.material_items FOR SELECT TO authenticated
  USING (active = true OR lower(auth.jwt() ->> 'email') = 'mtclemur@gmail.com');

CREATE POLICY "Material items admin write"
  ON public.material_items FOR ALL TO authenticated
  USING (lower(auth.jwt() ->> 'email') = 'mtclemur@gmail.com')
  WITH CHECK (lower(auth.jwt() ->> 'email') = 'mtclemur@gmail.com');

CREATE POLICY "Material requests select"
  ON public.material_requests FOR SELECT TO authenticated
  USING (
    auth.uid() = user_id
    OR lower(auth.jwt() ->> 'email') = 'mtclemur@gmail.com'
    OR EXISTS (
      SELECT 1 FROM public.workers worker
      WHERE lower(worker.email) = lower(auth.jwt() ->> 'email')
        AND lower(worker.role) = 'vorarbeiter'
    )
  );

CREATE POLICY "Material requests insert own"
  ON public.material_requests FOR INSERT TO authenticated
  WITH CHECK (auth.uid() IS NOT NULL AND user_id = auth.uid());

CREATE POLICY "Material requests update allowed"
  ON public.material_requests FOR UPDATE TO authenticated
  USING (
    auth.uid() = user_id
    OR lower(auth.jwt() ->> 'email') = 'mtclemur@gmail.com'
    OR EXISTS (
      SELECT 1 FROM public.workers worker
      WHERE lower(worker.email) = lower(auth.jwt() ->> 'email')
        AND lower(worker.role) = 'vorarbeiter'
    )
  )
  WITH CHECK (
    auth.uid() = user_id
    OR lower(auth.jwt() ->> 'email') = 'mtclemur@gmail.com'
    OR EXISTS (
      SELECT 1 FROM public.workers worker
      WHERE lower(worker.email) = lower(auth.jwt() ->> 'email')
        AND lower(worker.role) = 'vorarbeiter'
    )
  );

CREATE POLICY "Material request items select"
  ON public.material_request_items FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.material_requests request
      WHERE request.id = material_request_id
        AND (
          request.user_id = auth.uid()
          OR lower(auth.jwt() ->> 'email') = 'mtclemur@gmail.com'
          OR EXISTS (
            SELECT 1 FROM public.workers worker
            WHERE lower(worker.email) = lower(auth.jwt() ->> 'email')
              AND lower(worker.role) = 'vorarbeiter'
          )
        )
    )
  );

CREATE POLICY "Material request items insert"
  ON public.material_request_items FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.material_requests request
      WHERE request.id = material_request_id
        AND request.user_id = auth.uid()
    )
  );

CREATE POLICY "Inventory items read"
  ON public.inventory_items FOR SELECT TO authenticated
  USING (active = true OR lower(auth.jwt() ->> 'email') = 'mtclemur@gmail.com');

CREATE POLICY "Inventory items update allowed"
  ON public.inventory_items FOR UPDATE TO authenticated
  USING (auth.uid() IS NOT NULL)
  WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Inventory checkouts select"
  ON public.inventory_checkouts FOR SELECT TO authenticated
  USING (
    auth.uid() = user_id
    OR lower(auth.jwt() ->> 'email') = 'mtclemur@gmail.com'
    OR EXISTS (
      SELECT 1 FROM public.workers worker
      WHERE lower(worker.email) = lower(auth.jwt() ->> 'email')
        AND lower(worker.role) = 'vorarbeiter'
    )
  );

CREATE POLICY "Inventory checkouts insert own"
  ON public.inventory_checkouts FOR INSERT TO authenticated
  WITH CHECK (auth.uid() IS NOT NULL AND user_id = auth.uid());

CREATE POLICY "Inventory checkouts update allowed"
  ON public.inventory_checkouts FOR UPDATE TO authenticated
  USING (
    auth.uid() = user_id
    OR lower(auth.jwt() ->> 'email') = 'mtclemur@gmail.com'
    OR EXISTS (
      SELECT 1 FROM public.workers worker
      WHERE lower(worker.email) = lower(auth.jwt() ->> 'email')
        AND lower(worker.role) = 'vorarbeiter'
    )
  )
  WITH CHECK (
    auth.uid() = user_id
    OR lower(auth.jwt() ->> 'email') = 'mtclemur@gmail.com'
    OR EXISTS (
      SELECT 1 FROM public.workers worker
      WHERE lower(worker.email) = lower(auth.jwt() ->> 'email')
        AND lower(worker.role) = 'vorarbeiter'
    )
  );

INSERT INTO public.material_items (name, category, unit)
VALUES
  ('Schwarze Muellsaecke', 'verbrauchsmaterial', 'Rolle'),
  ('Blaue Muellsaecke', 'verbrauchsmaterial', 'Rolle'),
  ('Gelbe Saecke', 'verbrauchsmaterial', 'Rolle'),
  ('Handschuhe', 'schutz', 'Paar'),
  ('Papierhandtuecher', 'hygiene', 'Karton'),
  ('Toilettenpapier', 'hygiene', 'Karton'),
  ('Seife', 'hygiene', 'Kanister'),
  ('Desinfektionsmittel', 'hygiene', 'Flasche'),
  ('Wischbezuege', 'reinigung', 'Stueck'),
  ('Mikrofasertuecher', 'reinigung', 'Packung'),
  ('Schwaemme', 'reinigung', 'Packung'),
  ('Pads', 'reinigung', 'Stueck'),
  ('Abfallsaecke', 'verbrauchsmaterial', 'Rolle'),
  ('Reinigungsmittel auffuellen', 'chemie', 'Flasche'),
  ('Glasreiniger', 'chemie', 'Flasche'),
  ('Sanitaerreiniger', 'chemie', 'Flasche'),
  ('Allzweckreiniger', 'chemie', 'Flasche'),
  ('Grundreiniger', 'chemie', 'Kanister')
ON CONFLICT DO NOTHING;

INSERT INTO public.inventory_items (name, category, status)
VALUES
  ('Staubsauger 01', 'Staubsauger', 'verfuegbar'),
  ('Nasssauger 01', 'Nasssauger', 'verfuegbar'),
  ('Teppich-Extraktionsgeraet 01', 'Teppich-Extraktionsgeraet', 'verfuegbar'),
  ('Einscheibenmaschine 01', 'Einscheibenmaschine', 'verfuegbar'),
  ('Scheuersaugmaschine 01', 'Scheuersaugmaschine', 'verfuegbar'),
  ('Osmoseanlage 01', 'Osmoseanlage', 'verfuegbar'),
  ('Glasreinigungsset 01', 'Glasreinigungsset', 'verfuegbar'),
  ('Leiter 01', 'Leiter', 'verfuegbar'),
  ('Rollgeruest 01', 'Rollgeruest', 'verfuegbar'),
  ('Hochdruckreiniger 01', 'Hochdruckreiniger', 'verfuegbar'),
  ('Verlaengerungskabel 01', 'Verlaengerungskabel', 'verfuegbar'),
  ('Warnschild 01', 'Warnschild', 'verfuegbar')
ON CONFLICT DO NOTHING;

CREATE OR REPLACE FUNCTION public.sendDailyMaterialbedarfSummary()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Placeholder for a 21:00 Edge Function / cron call.
  -- The UI and tables already mark summary_sent / summary_sent_at.
  RETURN 'Use Supabase Edge Function send-materialbedarf-summary at 21:00 Europe/Berlin';
END;
$$;

NOTIFY pgrst, 'reload schema';
