-- CREATE workers table for Tagesbericht worker selection
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.workers (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  email text,
  phone text,
  active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.workers
  ADD COLUMN IF NOT EXISTS name text,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS phone text,
  ADD COLUMN IF NOT EXISTS active boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_workers_name ON public.workers(name);
CREATE INDEX IF NOT EXISTS idx_workers_active ON public.workers(active);

CREATE TABLE IF NOT EXISTS public.worker_time_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  report_id bigint,
  worker_id uuid REFERENCES public.workers(id) ON DELETE SET NULL,
  worker_name text NOT NULL,
  work_date date NOT NULL,
  object_id uuid,
  object_name text,
  auftragsnummer text,
  total_minutes integer DEFAULT 0,
  pause_minutes integer DEFAULT 0,
  auto_pause_minutes integer DEFAULT 0,
  fahrzeit_minutes integer DEFAULT 0,
  effective_minutes integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.worker_time_entries
  ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  ADD COLUMN IF NOT EXISTS report_id bigint,
  ADD COLUMN IF NOT EXISTS worker_id uuid REFERENCES public.workers(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS worker_name text,
  ADD COLUMN IF NOT EXISTS work_date date,
  ADD COLUMN IF NOT EXISTS object_id uuid,
  ADD COLUMN IF NOT EXISTS object_name text,
  ADD COLUMN IF NOT EXISTS auftragsnummer text,
  ADD COLUMN IF NOT EXISTS total_minutes integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pause_minutes integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS auto_pause_minutes integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fahrzeit_minutes integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS effective_minutes integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS idx_worker_time_report_worker_name
  ON public.worker_time_entries(report_id, worker_name);
CREATE INDEX IF NOT EXISTS idx_worker_time_date ON public.worker_time_entries(work_date);
CREATE INDEX IF NOT EXISTS idx_worker_time_worker_id ON public.worker_time_entries(worker_id);
CREATE INDEX IF NOT EXISTS idx_worker_time_object_id ON public.worker_time_entries(object_id);

DROP VIEW IF EXISTS public.worker_daily_totals;

CREATE VIEW public.worker_daily_totals AS
SELECT
  worker_id,
  worker_name,
  work_date,
  sum(total_minutes)::integer AS total_minutes,
  sum(pause_minutes)::integer AS pause_minutes,
  sum(auto_pause_minutes)::integer AS auto_pause_minutes,
  sum(fahrzeit_minutes)::integer AS fahrzeit_minutes,
  sum(effective_minutes)::integer AS effective_minutes,
  array_remove(array_agg(DISTINCT object_name), NULL) AS objects,
  array_remove(array_agg(DISTINCT auftragsnummer), NULL) AS auftragsnummern
FROM public.worker_time_entries
GROUP BY worker_id, worker_name, work_date;

ALTER TABLE public.workers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.worker_time_entries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Workers select authenticated" ON public.workers;
DROP POLICY IF EXISTS "Workers insert authenticated" ON public.workers;
DROP POLICY IF EXISTS "Workers update authenticated" ON public.workers;
DROP POLICY IF EXISTS "Worker time select authenticated" ON public.worker_time_entries;
DROP POLICY IF EXISTS "Worker time insert own" ON public.worker_time_entries;
DROP POLICY IF EXISTS "Worker time update own" ON public.worker_time_entries;
DROP POLICY IF EXISTS "Worker time delete own" ON public.worker_time_entries;

CREATE POLICY "Workers select authenticated"
  ON public.workers
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Workers insert authenticated"
  ON public.workers
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Workers update authenticated"
  ON public.workers
  FOR UPDATE
  TO authenticated
  USING (auth.uid() IS NOT NULL)
  WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Worker time select authenticated"
  ON public.worker_time_entries
  FOR SELECT
  TO authenticated
  USING (
    lower(auth.jwt() ->> 'email') = 'mtclemur@gmail.com'
    OR user_id = auth.uid()
    OR worker_name = (auth.jwt() ->> 'email')
    OR EXISTS (
      SELECT 1
      FROM public.workers
      WHERE workers.id = worker_time_entries.worker_id
        AND lower(workers.email) = lower(auth.jwt() ->> 'email')
    )
  );

CREATE POLICY "Worker time insert own"
  ON public.worker_time_entries
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() IS NOT NULL AND user_id = auth.uid());

CREATE POLICY "Worker time update own"
  ON public.worker_time_entries
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() IS NOT NULL AND user_id = auth.uid());

CREATE POLICY "Worker time delete own"
  ON public.worker_time_entries
  FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

NOTIFY pgrst, 'reload schema';
