-- CREATE TABLE and storage bucket for worker chat
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.chat_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  user_email text,
  sender_name text,
  message text,
  message_de text,
  source_language text,
  translated_at timestamptz,
  image_url text,
  image_path text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.chat_messages
  ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  ADD COLUMN IF NOT EXISTS user_email text,
  ADD COLUMN IF NOT EXISTS sender_name text,
  ADD COLUMN IF NOT EXISTS message text,
  ADD COLUMN IF NOT EXISTS message_de text,
  ADD COLUMN IF NOT EXISTS source_language text,
  ADD COLUMN IF NOT EXISTS translated_at timestamptz,
  ADD COLUMN IF NOT EXISTS image_url text,
  ADD COLUMN IF NOT EXISTS image_path text,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

ALTER TABLE public.chat_messages
ALTER COLUMN user_id SET DEFAULT auth.uid();

CREATE INDEX IF NOT EXISTS idx_chat_messages_created_at ON public.chat_messages(created_at);
CREATE INDEX IF NOT EXISTS idx_chat_messages_user_id ON public.chat_messages(user_id);

ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Chat select authenticated" ON public.chat_messages;
DROP POLICY IF EXISTS "Chat insert authenticated" ON public.chat_messages;
DROP POLICY IF EXISTS "Chat update own" ON public.chat_messages;
DROP POLICY IF EXISTS "Chat delete own" ON public.chat_messages;

CREATE POLICY "Chat select authenticated"
  ON public.chat_messages
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Chat insert authenticated"
  ON public.chat_messages
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() IS NOT NULL AND user_id = auth.uid());

CREATE POLICY "Chat update own"
  ON public.chat_messages
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Chat delete own"
  ON public.chat_messages
  FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

INSERT INTO storage.buckets (id, name, public)
VALUES ('chat-images', 'chat-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Chat images read" ON storage.objects;
DROP POLICY IF EXISTS "Chat images upload" ON storage.objects;

CREATE POLICY "Chat images read"
  ON storage.objects
  FOR SELECT
  TO authenticated
  USING (bucket_id = 'chat-images');

CREATE POLICY "Chat images upload"
  ON storage.objects
  FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id = 'chat-images' AND auth.uid() IS NOT NULL);

NOTIFY pgrst, 'reload schema';
