-- CREATE TABLE for Tagesbericht (reports)
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.tagesbericht (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  start_time timestamptz,
  object_id uuid REFERENCES public.objects(id),
  object_name text,
  auftragsnummer text,
  worker_ids uuid[],
  worker_names text[],
  task text,
  task_de text,
  damage_present boolean DEFAULT false,
  damage_description text,
  damage_description_de text,
  source_language text,
  translated_at timestamptz,
  damage_image_url text,
  damage_image_path text,
  customer_satisfied boolean DEFAULT true,
  customer_feedback text,
  customer_feedback_de text,
  client_signature_data_url text,
  end_time timestamptz,
  worker_email text,
  total_minutes integer DEFAULT 0,
  pause_minutes integer DEFAULT 0,
  auto_pause_minutes integer DEFAULT 0,
  fahrzeit_minutes integer DEFAULT 0,
  effective_minutes integer DEFAULT 0,
  pontaj_id bigint,
  created_at timestamptz DEFAULT now()
);

-- If the table already existed before these columns were added,
-- CREATE TABLE IF NOT EXISTS will not update it. These ALTERs keep it in sync.
ALTER TABLE public.tagesbericht
  ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS start_time timestamptz,
  ADD COLUMN IF NOT EXISTS object_id uuid REFERENCES public.objects(id),
  ADD COLUMN IF NOT EXISTS object_name text,
  ADD COLUMN IF NOT EXISTS auftragsnummer text,
  ADD COLUMN IF NOT EXISTS worker_ids uuid[],
  ADD COLUMN IF NOT EXISTS worker_names text[],
  ADD COLUMN IF NOT EXISTS task text,
  ADD COLUMN IF NOT EXISTS task_de text,
  ADD COLUMN IF NOT EXISTS damage_present boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS damage_description text,
  ADD COLUMN IF NOT EXISTS damage_description_de text,
  ADD COLUMN IF NOT EXISTS source_language text,
  ADD COLUMN IF NOT EXISTS translated_at timestamptz,
  ADD COLUMN IF NOT EXISTS damage_image_url text,
  ADD COLUMN IF NOT EXISTS damage_image_path text,
  ADD COLUMN IF NOT EXISTS customer_satisfied boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS customer_feedback text,
  ADD COLUMN IF NOT EXISTS customer_feedback_de text,
  ADD COLUMN IF NOT EXISTS client_signature_data_url text,
  ADD COLUMN IF NOT EXISTS end_time timestamptz,
  ADD COLUMN IF NOT EXISTS worker_email text,
  ADD COLUMN IF NOT EXISTS total_minutes integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pause_minutes integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS auto_pause_minutes integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fahrzeit_minutes integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS effective_minutes integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pontaj_id bigint,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

ALTER TABLE public.tagesbericht
ALTER COLUMN user_id SET DEFAULT auth.uid();

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'tagesbericht' AND column_name = 'pause_seconds') THEN
    EXECUTE 'UPDATE public.tagesbericht SET pause_minutes = COALESCE(NULLIF(pause_minutes, 0), ROUND(pause_seconds / 60.0)::integer)';
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'tagesbericht' AND column_name = 'auto_pause_seconds') THEN
    EXECUTE 'UPDATE public.tagesbericht SET auto_pause_minutes = COALESCE(NULLIF(auto_pause_minutes, 0), ROUND(auto_pause_seconds / 60.0)::integer)';
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'tagesbericht' AND column_name = 'fahrzeit_seconds') THEN
    EXECUTE 'UPDATE public.tagesbericht SET fahrzeit_minutes = COALESCE(NULLIF(fahrzeit_minutes, 0), ROUND(fahrzeit_seconds / 60.0)::integer)';
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'tagesbericht' AND column_name = 'total_seconds') THEN
    EXECUTE 'UPDATE public.tagesbericht SET total_minutes = COALESCE(NULLIF(total_minutes, 0), ROUND(total_seconds / 60.0)::integer)';
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'tagesbericht' AND column_name = 'effective_seconds') THEN
    EXECUTE 'UPDATE public.tagesbericht SET effective_minutes = COALESCE(NULLIF(effective_minutes, 0), ROUND(effective_seconds / 60.0)::integer)';
  END IF;
END $$;

ALTER TABLE public.tagesbericht
DROP COLUMN IF EXISTS pause_seconds,
DROP COLUMN IF EXISTS auto_pause_seconds,
DROP COLUMN IF EXISTS fahrzeit_seconds,
DROP COLUMN IF EXISTS total_seconds,
DROP COLUMN IF EXISTS effective_seconds;

CREATE INDEX IF NOT EXISTS idx_tages_user_id ON public.tagesbericht(user_id);
CREATE INDEX IF NOT EXISTS idx_tages_object_id ON public.tagesbericht(object_id);
CREATE INDEX IF NOT EXISTS idx_tages_pontaj_id ON public.tagesbericht(pontaj_id);
CREATE INDEX IF NOT EXISTS idx_tages_worker_ids ON public.tagesbericht USING gin(worker_ids);

-- Enable RLS and policies
ALTER TABLE public.tagesbericht ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Select own reports" ON public.tagesbericht;
DROP POLICY IF EXISTS "Select allowed reports" ON public.tagesbericht;
DROP POLICY IF EXISTS "Insert own reports" ON public.tagesbericht;
DROP POLICY IF EXISTS "Update own reports" ON public.tagesbericht;
DROP POLICY IF EXISTS "Delete own reports" ON public.tagesbericht;

CREATE POLICY "Select allowed reports"
  ON public.tagesbericht
  FOR SELECT
  TO authenticated
  USING (
    lower(auth.jwt() ->> 'email') = 'mtclemur@gmail.com'
    OR auth.uid() = user_id
    OR lower(worker_email) = lower(auth.jwt() ->> 'email')
    OR EXISTS (
      SELECT 1
      FROM public.workers
      WHERE workers.id = ANY(tagesbericht.worker_ids)
        AND lower(workers.email) = lower(auth.jwt() ->> 'email')
    )
  );
CREATE POLICY "Insert own reports" ON public.tagesbericht FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL AND user_id = auth.uid());
CREATE POLICY "Update own reports" ON public.tagesbericht FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() IS NOT NULL AND user_id = auth.uid());
CREATE POLICY "Delete own reports" ON public.tagesbericht FOR DELETE TO authenticated USING (auth.uid() = user_id);

INSERT INTO storage.buckets (id, name, public)
VALUES ('report-images', 'report-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Report images read" ON storage.objects;
DROP POLICY IF EXISTS "Report images upload" ON storage.objects;

CREATE POLICY "Report images read"
  ON storage.objects
  FOR SELECT
  TO authenticated
  USING (bucket_id = 'report-images');

CREATE POLICY "Report images upload"
  ON storage.objects
  FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id = 'report-images' AND auth.uid() IS NOT NULL);

NOTIFY pgrst, 'reload schema';
