-- Voqenti learning items: small daily A2/B1 German phrases for the dashboard
-- Run this in Supabase SQL Editor.
-- This script does not use public.profiles. Roles are read from public.workers.

CREATE TABLE IF NOT EXISTS public.learning_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  german_text text NOT NULL,
  ro_translation text NOT NULL,
  ru_translation text NOT NULL,
  german_example text,
  ro_example text,
  ru_example text,
  level text DEFAULT 'A2/B1',
  category text DEFAULT 'Alltag',
  active boolean DEFAULT true,
  shown_date date,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.learning_items
  ADD COLUMN IF NOT EXISTS german_text text,
  ADD COLUMN IF NOT EXISTS ro_translation text,
  ADD COLUMN IF NOT EXISTS ru_translation text,
  ADD COLUMN IF NOT EXISTS german_example text,
  ADD COLUMN IF NOT EXISTS ro_example text,
  ADD COLUMN IF NOT EXISTS ru_example text,
  ADD COLUMN IF NOT EXISTS level text DEFAULT 'A2/B1',
  ADD COLUMN IF NOT EXISTS category text DEFAULT 'Alltag',
  ADD COLUMN IF NOT EXISTS active boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS shown_date date,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_learning_items_active_date
  ON public.learning_items(active, shown_date, created_at);

ALTER TABLE public.learning_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Learning items read authenticated" ON public.learning_items;
DROP POLICY IF EXISTS "Learning items update shown date" ON public.learning_items;
DROP POLICY IF EXISTS "Learning items admin write" ON public.learning_items;

CREATE POLICY "Learning items read authenticated"
  ON public.learning_items
  FOR SELECT
  TO authenticated
  USING (active = true OR lower(auth.jwt() ->> 'email') = 'mtclemur@gmail.com');

CREATE POLICY "Learning items update shown date"
  ON public.learning_items
  FOR UPDATE
  TO authenticated
  USING (auth.uid() IS NOT NULL)
  WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Learning items admin write"
  ON public.learning_items
  FOR INSERT
  TO authenticated
  WITH CHECK (
    lower(auth.jwt() ->> 'email') = 'mtclemur@gmail.com'
    OR EXISTS (
      SELECT 1 FROM public.workers
      WHERE lower(workers.email) = lower(auth.jwt() ->> 'email')
        AND lower(COALESCE(workers.role, 'mitarbeiter')) IN ('admin', 'vorarbeiter')
    )
  );

INSERT INTO public.learning_items
  (german_text, ro_translation, ru_translation, german_example, ro_example, ru_example, level, category)
VALUES
  ('Das kommt darauf an.', 'Depinde.', 'Это зависит.', 'Das kommt darauf an, wann wir fertig sind.', 'Depinde de când terminăm.', 'Это зависит от того, когда мы закончим.', 'A2/B1', 'Alltag'),
  ('Ich bin unterwegs.', 'Sunt pe drum.', 'Я в пути.', 'Ich bin unterwegs und komme in 20 Minuten.', 'Sunt pe drum și ajung în 20 de minute.', 'Я в пути и буду через 20 минут.', 'A2', 'Alltag'),
  ('Ich kümmere mich darum.', 'Mă ocup de asta.', 'Я этим займусь.', 'Keine Sorge, ich kümmere mich darum.', 'Nu vă faceți griji, mă ocup de asta.', 'Не волнуйтесь, я этим займусь.', 'B1', 'Arbeit'),
  ('Könnten Sie das bitte wiederholen?', 'Ați putea repeta, vă rog?', 'Не могли бы Вы повторить?', 'Entschuldigung, könnten Sie das bitte wiederholen?', 'Scuzați, ați putea repeta, vă rog?', 'Извините, не могли бы Вы повторить?', 'A2', 'Kommunikation'),
  ('Ich melde mich später.', 'Revin mai târziu.', 'Я свяжусь позже.', 'Ich melde mich später mit den Informationen.', 'Revin mai târziu cu informațiile.', 'Я позже сообщу информацию.', 'A2/B1', 'Kommunikation'),
  ('Das ist erledigt.', 'Este rezolvat.', 'Это сделано.', 'Die Aufgabe ist erledigt.', 'Sarcina este rezolvată.', 'Задача выполнена.', 'A2', 'Arbeit'),
  ('Ich habe eine Frage.', 'Am o întrebare.', 'У меня есть вопрос.', 'Ich habe eine Frage zum Auftrag.', 'Am o întrebare despre comandă.', 'У меня вопрос по заказу.', 'A1/A2', 'Kommunikation'),
  ('Können wir kurz sprechen?', 'Putem vorbi puțin?', 'Можем коротко поговорить?', 'Können wir kurz über den Plan sprechen?', 'Putem vorbi puțin despre plan?', 'Можем коротко поговорить о плане?', 'A2', 'Arbeit'),
  ('Ich brauche Hilfe.', 'Am nevoie de ajutor.', 'Мне нужна помощь.', 'Ich brauche Hilfe mit dem Gerät.', 'Am nevoie de ajutor cu echipamentul.', 'Мне нужна помощь с оборудованием.', 'A2', 'Arbeit'),
  ('Das ist dringend.', 'Este urgent.', 'Это срочно.', 'Der Kunde sagt, das ist dringend.', 'Clientul spune că este urgent.', 'Клиент говорит, что это срочно.', 'A2', 'Arbeit'),
  ('Ich bin gleich da.', 'Ajung imediat.', 'Я сейчас буду.', 'Ich bin gleich da, bitte warten Sie kurz.', 'Ajung imediat, vă rog așteptați puțin.', 'Я сейчас буду, пожалуйста, подождите немного.', 'A2', 'Alltag'),
  ('Das passt so.', 'Așa este bine.', 'Так подходит.', 'Ja, das passt so.', 'Da, așa este bine.', 'Да, так подходит.', 'A2', 'Alltag'),
  ('Ich habe es verstanden.', 'Am înțeles.', 'Я понял/поняла.', 'Danke, ich habe es verstanden.', 'Mulțumesc, am înțeles.', 'Спасибо, я понял/поняла.', 'A2', 'Kommunikation'),
  ('Könnten Sie mir bitte zeigen, wo ... ist?', 'Îmi puteți arăta unde este ...?', 'Не могли бы Вы показать, где ...?', 'Könnten Sie mir bitte zeigen, wo der Eingang ist?', 'Îmi puteți arăta unde este intrarea?', 'Не могли бы Вы показать, где вход?', 'A2/B1', 'Alltag'),
  ('Ich bin heute bis 16 Uhr da.', 'Astăzi sunt aici până la ora 16.', 'Сегодня я здесь до 16:00.', 'Ich bin heute bis 16 Uhr da, danach bin ich unterwegs.', 'Astăzi sunt aici până la ora 16, după aceea sunt pe drum.', 'Сегодня я здесь до 16:00, потом буду в пути.', 'A2', 'Arbeit'),
  ('Das wurde bereits gemacht.', 'Asta a fost deja făcut.', 'Это уже было сделано.', 'Die Kontrolle wurde bereits gemacht.', 'Controlul a fost deja făcut.', 'Проверка уже была сделана.', 'B1', 'Arbeit'),
  ('Ich gebe Bescheid.', 'Anunț.', 'Я сообщу.', 'Ich gebe Bescheid, wenn wir fertig sind.', 'Anunț când terminăm.', 'Я сообщу, когда мы закончим.', 'A2/B1', 'Kommunikation'),
  ('Das fehlt noch.', 'Asta încă lipsește.', 'Этого еще не хватает.', 'Ein Teil fehlt noch.', 'O parte încă lipsește.', 'Одной части еще не хватает.', 'A2', 'Arbeit'),
  ('Wir schaffen das.', 'Ne descurcăm.', 'Мы справимся.', 'Es ist viel Arbeit, aber wir schaffen das.', 'Este mult de lucru, dar ne descurcăm.', 'Работы много, но мы справимся.', 'A2/B1', 'Motivation'),
  ('Bitte prüfen Sie das noch einmal.', 'Vă rog verificați încă o dată.', 'Пожалуйста, проверьте еще раз.', 'Bitte prüfen Sie das noch einmal, bevor wir gehen.', 'Vă rog verificați încă o dată înainte să plecăm.', 'Пожалуйста, проверьте еще раз, прежде чем мы уйдем.', 'B1', 'Arbeit'),
  ('Ich bin mir nicht sicher.', 'Nu sunt sigur.', 'Я не уверен/уверена.', 'Ich bin mir nicht sicher, ob das richtig ist.', 'Nu sunt sigur dacă este corect.', 'Я не уверен/уверена, правильно ли это.', 'A2/B1', 'Kommunikation'),
  ('Das ist kein Problem.', 'Nu este o problemă.', 'Это не проблема.', 'Das ist kein Problem, wir machen das morgen.', 'Nu este o problemă, facem asta mâine.', 'Это не проблема, мы сделаем это завтра.', 'A2', 'Alltag'),
  ('Ich habe keine Internetverbindung.', 'Nu am conexiune la internet.', 'У меня нет подключения к интернету.', 'Ich habe gerade keine Internetverbindung.', 'Acum nu am conexiune la internet.', 'У меня сейчас нет подключения к интернету.', 'A2', 'Alltag'),
  ('Können Sie mir die Adresse schicken?', 'Îmi puteți trimite adresa?', 'Можете отправить мне адрес?', 'Können Sie mir die Adresse per WhatsApp schicken?', 'Îmi puteți trimite adresa pe WhatsApp?', 'Можете отправить мне адрес в WhatsApp?', 'A2', 'Alltag'),
  ('Ich komme etwas später.', 'Ajung puțin mai târziu.', 'Я приеду немного позже.', 'Wegen Verkehr komme ich etwas später.', 'Din cauza traficului ajung puțin mai târziu.', 'Из-за пробок я приеду немного позже.', 'A2', 'Alltag')
ON CONFLICT DO NOTHING;

NOTIFY pgrst, 'reload schema';
