-- CREATE email outbox for Tagesbericht test sending
-- Run this in Supabase SQL Editor after SETUP_REPORTS.sql

CREATE TABLE IF NOT EXISTS public.email_outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  report_id bigint REFERENCES public.tagesbericht(id) ON DELETE CASCADE,
  recipient text NOT NULL,
  subject text NOT NULL,
  html_body text,
  payload jsonb DEFAULT '{}'::jsonb,
  status text DEFAULT 'pending',
  error_message text,
  sent_at timestamptz,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.email_outbox
  ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  ADD COLUMN IF NOT EXISTS report_id bigint REFERENCES public.tagesbericht(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS recipient text,
  ADD COLUMN IF NOT EXISTS subject text,
  ADD COLUMN IF NOT EXISTS html_body text,
  ADD COLUMN IF NOT EXISTS payload jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS error_message text,
  ADD COLUMN IF NOT EXISTS sent_at timestamptz,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_email_outbox_status ON public.email_outbox(status);
CREATE INDEX IF NOT EXISTS idx_email_outbox_report_id ON public.email_outbox(report_id);
CREATE INDEX IF NOT EXISTS idx_email_outbox_created_at ON public.email_outbox(created_at);

ALTER TABLE public.email_outbox ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Email outbox select own" ON public.email_outbox;
DROP POLICY IF EXISTS "Email outbox insert own" ON public.email_outbox;
DROP POLICY IF EXISTS "Email outbox update own" ON public.email_outbox;

CREATE POLICY "Email outbox select own"
  ON public.email_outbox
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Email outbox insert own"
  ON public.email_outbox
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() IS NOT NULL AND user_id = auth.uid());

CREATE POLICY "Email outbox update own"
  ON public.email_outbox
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() IS NOT NULL AND user_id = auth.uid());

NOTIFY pgrst, 'reload schema';
